server:
  port: 8082 # El módulo Table Management usa el 8081

spring:
  application:
    name: ordering-service
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db # Comparten DB o usa otra si prefieres
    username: user
    password: password

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
